### ISSUE TITLE
Implement functions of the explorer

### ISSUE THREAD

**Issue by BECATRUE** [snu-quiqcl/iquip#10]
### Feature you want to implement
I want to add all functions of the explorer app.

As I wrote in #6, there are 3 goals.
- Show the directory structure where `artiq_master` is running.
- Able to reload the directory structure. (It may be updated during operation)
- ~~Open the experiment builder once an experiment clicked.~~ (will be implemented later)

We can only implement the last one perfectly after the experiment builder is completed, so I just add an empty function to open it and the other parts will be implemented in the later issue.

#### Show the directory structure
- You may be not able to access the root of `artiq_master` because you connect in remote. So we cannot use [QFileDialog](https://doc.qt.io/qt-5/qfiledialog.html).
- Instead, we can use [QTreeView](https://doc.qt.io/qtforpython-5/PySide2/QtWidgets/QTreeView.html#qtreeview).
- The example GUI is as follows.
<img weight="50%" src="https://github.com/snu-quiqcl/iquip/assets/76851886/5944d565-4acb-4b36-ba13-ae7380a31670">

#### Reload the directory structure
- Create a button to request for reloading.

#### ~~Open the experiment builder (will be implemented later)~~
- Once you clicked an experiment in the above `QTreeView`, reqeust to open the experiment builder through `qiwiscall`.

### Additional context
As I wrote in the obsidian note, in this issue, we can use only the default `artiq_master` options.
See the note for details.

**Comment by kangz12345** [comment]
> Able to reload the directory structure. (It may be updated during operation)

What do you mean by "It may be updated during operation"?

**Comment by BECATRUE** [comment]
> > Able to reload the directory structure. (It may be updated during operation)
> 
> What do you mean by "It may be updated during operation"?

It means that while you run the `iquip` GUI, someone (it may be yourself!) can add or remove an experiment file.
In that case, the explorer cannot update the file structure automatically because it doesn't poll the structure.
So I will add a button to update it.

**Comment by kangz12345** [comment]
Oh I see! Thank you for the explanation 👍
