### ISSUE TITLE
Set another viewer for deleted/terminated/completed experiments.

### ISSUE THREAD

**Issue by giwon2004** [snu-quiqcl/iquip#106]
### Feature you want to implement
I want to set another viewer to list experiments that are not on the scheduler now but were on the scheduler.

### How the feature is implemented
The deleted, terminated experiments will now be sent to another `QListView` that holds them.
When the experiment is gone after its `status` being `"deleting"`, that experiment will be also listed in that `QListView` instance.

Right-clicking them will show another `QMenu` with one element: `Restart experiment`, submitting the same experiment again.
This feature would use the [code in artiq-proxy](https://github.com/snu-quiqcl/artiq-proxy/blob/develop/main.py#L148) that was not originally meant to be used by `scheduler.py`.

**Comment by kangz12345** [comment]
Great. Will it be another app, or just another frame in the same app (`SchedulerApp`)?

**Comment by giwon2004** [comment]
For now, I think it will be inside the same app, with two parallel lists.

**Comment by kangz12345** [comment]
As the previous GUI is deprecated, I close this issue.
However, the feature would be necessary and might be implemented later.
