### ISSUE TITLE
[BUG] Several errors when fetching the scheduled queue

### ISSUE THREAD

**Issue by BECATRUE** [snu-quiqcl/iquip#132]
### Describe the bug
There are two main problems:
- The scheduler app is fetching the queue so slowly. Even though I submit several experiments, there is no update.
I didn't look up this deeply, so it may be a problem of ARTIQ-PROXY, not here.
- Once fetching the queue, the following error occurs.
<img width="60%" src="https://github.com/snu-quiqcl/iquip/assets/76851886/7b90f4f5-4eb1-4d12-908e-3ad5f13977fe">

**Comment by kangz12345** [comment]
Did you apply the change #129?

**Comment by BECATRUE** [comment]
> Did you apply the change https://github.com/snu-quiqcl/iquip/pull/129?

I will check it!

Also, the first bug seems to be referred to #136 by @giwon2004.

**Comment by BECATRUE** [comment]
I pulled the `develop` branch a few minutes ago, but the same error occurs.

**Comment by BECATRUE** [comment]
I renewed the scheduler app in #181, so I close this issue.
