### ISSUE TITLE
Make the unittests not failed

### ISSUE THREAD

**Issue by BECATRUE** [snu-quiqcl/iquip#134]
### Feature you want to implement
For keeping this project safe and releasing the next version, I think in terms of GitHub actions, we don't have to reach 100% cover, but we MUST make them even not failed.
So after resolving #124, I will make Pylint and Unittest not failed.

**Comment by BECATRUE** [comment]
What do you think of this? @kangz12345

**Comment by kangz12345** [comment]
I didn't get your point. Are you going to resolve #124? Or do you want to postpone it?
Also, pylint test is passing now.

**Comment by BECATRUE** [comment]
I didn't think #124 won't resolve all GitHub actions, but it did so😃

So, this issue isn't necessary anymore!
