### ISSUE TITLE
`DataViewerApp` with minimal features

### ISSUE THREAD

**Issue by kangz12345** [snu-quiqcl/iquip#144]
#### 1. Source selection
- Realtime: "Sync" button to synchronize with the current artiq master. The RID information is shown.
- Remote: Type the desired RID in a spinbox to get the result data. The execution date is shown.
- Local: Will not be implemented in this issue.

#### 2. Data point
- Threshold spinbox (whose prefix is ">" which indicates that the threshold is exclusive).
- P1: Population of the state 1 based on the threshold.
- Average: Average photon count.
- Total: Total photon count.
P1/Average/Total are in a radio button group, so the selected value will be used for the main plot.
- Histogram plot (`BarGraphItem`) with the threshold vertical line.

<img width="508" alt="image" src="https://github.com/snu-quiqcl/iquip/assets/8445906/703898b4-2510-499d-9167-77dc960462e7">

#### 3. Main plot
- The main plot based on the selected value in "Data point" section.
- The plot type is switched based on the dimension of the data.
- If the user click a data point, its histogram is shown in "Data point" section.

### 4. Tools
- This will not be implemented in this issue.

See also: #143

## Subtasks
- #146 
- #151
- #156
- #160
- #164
- #176

**Comment by kangz12345** [comment]
Oh, since I created the branch from this issue, #146 unintentionally closed this issue.

**Comment by BECATRUE** [comment]
I think the example plot (in your hand painting) will be shown when the P1 radio button is selected.
Then, what plot will be shown when the other radio button is selected?

**Comment by kangz12345** [comment]
The radio button does not change the plot here. Instead, it will change the main plot.
The histogram is helpful regardless of the main plot type (total/average/p1).

**Comment by BECATRUE** [comment]
Oh, I understand it now! Thanks😃
