### ISSUE TITLE
Single TTL monitor widget

### ISSUE THREAD

**Issue by kangz12345** [snu-quiqcl/iquip#15]
### Feature you want to implement
A widget and object which monitors a~~n ARTIQ~~ TTL input or output.
~~When the input or output changes, the monitor should be able to notice it. (See #17)~~
Note that this does not include any `qiwi` app.
It will be implemented in the next issue.

### How the feature is implemented
Create a module `monitor.py` and implement classes ~~`TTLMonitor`~~ `Monitor` and `TTLMonitorWidget`.

#### ~~`TTLMonitor`~~
- It is a non-GUI object which monitors a single TTL channel.
- Specific implementation will be decided later.

#### `Monitor`
- It defines the monitor interface.

#### `TTLMonitorWidget`
- It is a PyQt widget for displaying a single TTL channel status.
- It does not include the proper slot connections to actually update the status. It only includes the GUI part, without the core logic.

### Additional context
See also: #12

**Comment by BECATRUE** [comment]
> It will be implemented in the next issue.

What will be implemented in the next issue?

**Comment by BECATRUE** [comment]
In according to your plan, is the `TTLMonitor` a subclass of `BaseApp` and is the `TTLMonitorWidget` a frame of the former class?

**Comment by kangz12345** [comment]
> What will be implemented in the next issue?

The `qiwis` app and frames will be implemented later.

> In according to your plan, is the `TTLMonitor` a subclass of `BaseApp` and is the `TTLMonitorWidget` a frame of the former class?

No, the classes implemented in this issue are independent to `qiwis`.
They will be used to implement `qiwis` apps and frames.

**Comment by BECATRUE** [comment]
Now I understand! Thanks for your explanation.
