### ISSUE TITLE
Single ARTIQ DDS monitor widget

### ISSUE THREAD

**Issue by kangz12345** [snu-quiqcl/iquip#16]
### Feature you want to implement
Implement a single ARTIQ DDS (Urukul) channel monitor widget, which should be updated whenever the DDS channel output is changed (e.g., frequency, amplitude, phase, etc.).
The exact monitoring values depend on the ARTIQ DDS library support.

@Ahrrri Please fill out this issue and implement the feature. I think [artiq.dashboard.moninj](https://github.com/m-labs/artiq/blob/df15f53ee97558b31c23a3bbe93f32c14b18fe74/artiq/dashboard/moninj.py) would be a good point to start from.

### How the feature is implemented
ex) Add *B* method to *A* class, Upgrade *C* model

### Additional context
Add any other context or screenshots about the feature here.

**Comment by BECATRUE** [comment]
Is it okay to close this issue? @kangz12345

**Comment by BECATRUE** [comment]
Oh, I intended just to ask you, but I mistaked to close this😅
If this issue is still necessary, please reopen it.
