### ISSUE TITLE
Result RID sorting order in `result_explorer`

### ISSUE THREAD

**Issue by kangz12345** [snu-quiqcl/iquip#165]
### Feature you want to implement
It would be better to sort the RIDs in descending order, to show the recent data at the top.

**Comment by BECATRUE** [comment]
Oh, I strongly agree with it. In current system, the proxy server offers the RIDs in ascending order.
Then which is better 1. sorting it in IQUIP or 2. making the proxy server offer the RIDs in descending order?

**Comment by kangz12345** [comment]
Since the proxy server needs a convention of the returned RID list order, so I think the server should sort it in descending order.

**Comment by BECATRUE** [comment]
Now, this issue is responsible for ARTIQ-RROXY, so I created snu-quiqcl/artiq-proxy#77 and closed this issue.
