### ISSUE TITLE
New `SchedulerApp`

### ISSUE THREAD

**Issue by BECATRUE** [snu-quiqcl/iquip#181]
_(updated)_

### Feature you want to implement
I will develop a new version of scheduler app because of the following reasons:
- `QAbstractTableModel` looks more useful than `QAbstractListModel` since the scheduled experiment list is a 2D dataset;
a row is each experiment, and a column is each info in an experiment.
- In current scheduler app, there are several bugs.

### How the feature is implemented
Basically, it will be implemented under the [model/view architecture](https://doc.qt.io/qtforpython-5/overviews/model-view-programming.html).
If you're not familiar to this, I strongly recommend to read it. (I'm also unfamilar to it..😅)

I briefly separate this issue into five minor issues:
1. Construct the model/view architecture in order to show the given scheduled queue.
#182 
2. Fetch the actual queue from the proxy server, and apply it actively.
#185 
3. Enable to delete and terminate a specific experiment.
#192
4. ~~Support various sorting.~~
~~#193~~
5. ~~Enable to modify a specific queued experiment.~~

**Comment by BECATRUE** [comment]
@kangz12345 
Is the final issue; modifying a specific queued experiment, necessary?
I planned that issue, but I don't know well if it is really necessary.

**Comment by kangz12345** [comment]
I don't think it is necessary for now. You can postpone that issue.
