### ISSUE TITLE
`selectDataPoint` fails when a dataset is loaded

### ISSUE THREAD

**Issue by BECATRUE** [snu-quiqcl/iquip#203]
### Describe the bug
When a new dataset is loaded, an exception occurs.

<img width="90%" src="https://github.com/snu-quiqcl/iquip/assets/76851886/0433ab6b-768c-492d-a17e-e25b1db22767">

### To Reproduce
1. Type a dataset name.
2. Turn on polling for a while.
3. Set an appropriate axis.
4. Click "Apply" button.

### Expected causes and correction methods
As I debugged, [DataViewerApp.dataPoint()](https://github.com/snu-quiqcl/iquip/blob/develop/iquip/apps/dataviewer.py#L984) doesn't support `index` with `(-1,)`.

Once loaded, `DataViewerApp.selectDataPoint()` is called in [here](DataViewerApp), and it calls `dataPoint()` in [here](https://github.com/snu-quiqcl/iquip/blob/develop/iquip/apps/dataviewer.py#L998) with `index = (-1,)`.
And it causes an error in `data_indices = np.all(symbols.T == index, axis=1)` since `symbols.T` never has `(-1,)`.

**Comment by BECATRUE** [comment]
Please check this bug! @kangz12345

**Comment by kangz12345** [comment]
Great, your correction method works!
