### ISSUE TITLE
Provide exception information in `cmdtools.run_command()`

### ISSUE THREAD

**Issue by kangz12345** [snu-quiqcl/iquip#22]
### What feature do you want to suggest?
To provide the exception information in `cmdtools.run_command()`.
If there is no more feature in `cmdtools`, we can use just `subprocess` directly.

_Originally posted by @kangz12345 in https://github.com/snu-quiqcl/iquip/pull/19#discussion_r1204870918_

**Comment by BECATRUE** [comment]
As we decided, we will implement a proxy server to communicate with ARTIQ and send a reqeust through this, not directly.
Thus, `cmdtools` module is not used in the future.

**Comment by BECATRUE** [comment]
As we decided, we will implement a proxy server to communicate with ARTIQ and send a reqeust through this, not directly.
Thus, `cmdtools` module is not used in the future.
