### ISSUE TITLE
Add Center Scan and Explicit Scan

### ISSUE THREAD

**Issue by Aijuh** [snu-quiqcl/iquip#229]
### Feature you want to implement
Add widget for center scan, explicit scan at builder GUI.

### How the feature is implemented
1. Add widget for center scan and explicit scan.
2. Modify `_ScanEntry` class to support new scan type widget.

**Comment by BECATRUE** [comment]
@kangz12345 I have a question in terms of UX.

In ARTIQ dashboard, an explicit scan widget offers only a string input widget and a user should write the desired sequence with delimiters. (I don't remember well, but I think it is either comma or space.)
It might seem to be crude, and a user has difficulties to see a long sequence and reorder it. But it also has an advantage that a user can copy the sequence easily.

Of course, we can make a neater UI, for example, once a space is typed, the previous string becomes an item (widget), and we can reorder them easily by dragging. (similar to hashtag in Obsidian even if they cannot be reordered.)

From the experimenter's point of view, I wonder which one is preferred, a too simple UI or a complex but functional UI.

**Comment by kangz12345** [comment]
I think such features are too fancy for us as we are not going to use it that much.
Instead, supporting python script including `numpy` API, e.g., `[4, 7, 2]` or `np.linspace(0., 100., 11, endpoint=True)`, would be helpful.
Also, this can be implemented via `eval` I guess.

**Comment by BECATRUE** [comment]
I see. Your suggestion looks more efficient.

@Aijuh Can you apply this decision? I think it is okay to implement it in the next issue.

If you can't afford it because of your work, I'll do it.
