### ISSUE TITLE
Motorized stage monitor

### ISSUE THREAD

**Issue by kangz12345** [snu-quiqcl/iquip#245]
### Feature you want to implement
A simple (controllable) monitor for motorized stages.
- Realtime position update.
- Absolute move.
- Relative move.

### How the feature is implemented
A new app "controller" will be added, which is for non-artiq devices.

### Subtasks
- [x] #248 
- [x] #275
- [x] #285

**Comment by BECATRUE** [comment]
Is there any better app name instead of "controller"?
The "monitor" app actually serves as a controller, so I think it would be better to set a name that highlights "NDSP" such as "networkMonitor".

**Comment by BECATRUE** [comment]
What does the subtask "`qiwis` app" mean? @kangz12345

**Comment by BECATRUE** [comment]
Oh, it means just an app for controlling these devices!
