### ISSUE TITLE
More compact builder UI

### ISSUE THREAD

**Issue by kangz12345** [snu-quiqcl/iquip#254]
### Feature you want to implement
How about putting the argument, scan parameter, schedule option panels into tabs to make each builder frame smaller?

### How the feature is implemented
Each builder frame has 3 tabs: argument, scan parameter, schedule option.

### Additional context
Currently each builder frame is too large (the empty scan parameter panel consumes a lot of display area) and it is quite inconvenient.

**Comment by BECATRUE** [comment]
I've been thinking the current builder is too large, so your suggestion looks reasonable👍

Is it okay to implement this right now? @kangz12345

**Comment by kangz12345** [comment]
> Is it okay to implement this right now? @kangz12345 

Yeah sure!

**Comment by BECATRUE** [comment]
Using [`QTabWidget`](https://doc.qt.io/qtforpython-5/PySide2/QtWidgets/QTabWidget.html#), it seems to be implemented easily.
