### ISSUE TITLE
Error when changing time or rid rapidly (dataviewer remote)

### ISSUE THREAD

**Issue by kangz12345** [snu-quiqcl/iquip#277]
### Describe the bug
When I change the hour or rid very fast (using mouse wheel), iquip crashes or printing the error below:
```shell
Traceback (most recent call last):
  File "C:\Users\QC109_3\iquip\iquip\apps\dataviewer.py", line 1224, in _handleDatasetClicked
    self.startRemoteDatasetThread(name)
  File "C:\Users\QC109_3\iquip\iquip\apps\dataviewer.py", line 1340, in startRemoteDatasetThread
    rid = int(self.remotePart.ridComboBox.currentText())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: ''
```

### Expected behavior
The program should be stable even if the hour or rid is changed rapidly.

### To Reproduce
1. Open iquip with dataviewer.
2. Scroll the mouse wheel on the rid combobox.
3. The program exits.

**Comment by BECATRUE** [comment]
As I tested, it is sufficient to check if the previous thread is running when the current value is changed.
So, I will fix it like this.
