### ISSUE TITLE
Scan argument scale for common units (e.g. us) is not applied

### ISSUE THREAD

**Issue by kangz12345** [snu-quiqcl/iquip#303]
### Describe the bug
When I use a `Scannable(RangeScan(0., 100*us, 21, True), unit="us"))` and submit the experiment through iquip, the obtained values are not scaled by 1e-6. In other words, they are (0., 5., 10., ...) instead of (0., 5e-6, 1e-5, ...).

### Expected behavior
The appropriate scale should be applied for the common units.

**Comment by BECATRUE** [comment]
Oh, as you said, ARTIQ also handles the entry value applied for its scale!
(ref. https://github.com/m-labs/artiq/blob/56bd975a347155181cf1fdd5fc383742d22daf57/artiq/gui/entries.py#L311)
