### ISSUE TITLE
Handle an empty `choices` of enumeration value

### ISSUE THREAD

**Issue by BECATRUE** [snu-quiqcl/iquip#55]
As we discussed in #47, an empty `choices` of enumeration value doesn't cause an error before submission, but it CANNOT be successful due to an empty value.
So, we should handle that case.

_Originally posted by @kangz12345 in https://github.com/snu-quiqcl/iquip/pull/47#discussion_r1252489188_

**Comment by BECATRUE** [comment]
I think it is enough to leave a `WARNING` or `ERROR` log because it is not a problem in terms of IQUIP, but just the experiment code.
What do you think of it? @kangz12345

**Comment by kangz12345** [comment]
Yes, I think it should leave an `ERROR` log and not open the builder window (or, if it should be checked in the builder app, terminate the builder app).

**Comment by BECATRUE** [comment]
How about just showing a warning alert?
I think it is enough because even after opening the builder, the user can fix the experiment code and apply it to GUI by clicking the reload button.

In addition, let's imagine the following situation.
1. Open a builder.
2. Update the experiment code to make `choices` empty.
3. Reload the build arguments.

In that case, terminating the builder app looks a little awkward.

Thus, I think alerting is enough.

@kangz12345

**Comment by kangz12345** [comment]
Okay then does it alert when the user tries to submit the experiment (when the submit button is clicked)?

**Comment by BECATRUE** [comment]
Originally I planned that it alerts when the builder app is created or reloaded, but you suggestion would be better!
