### ISSUE TITLE
List pending experiments and displaying currently running experiment in `scheduler.py`

### ISSUE THREAD

**Issue by giwon2004** [snu-quiqcl/iquip#63]
### Feature you want to implement
Implement a scheduler that shows the list of experiments and their status

### How the feature is implemented
In `iquip/apps`, make a new file named `scheduler.py` to implement the GUI, using `qiwis`, according to the python code [artiq/artiq/dashboard/schedule.py](https://github.com/m-labs/artiq/blob/master/artiq/dashboard/schedule.py).

It adds a layout that has `QListView` for listing pending experiments. (Class `ScheduleDock` in [artiq/artiq/dashboard/schedule.py](https://github.com/m-labs/artiq/blob/master/artiq/dashboard/schedule.py) used `QTableView` to show information like `expid` and `status` in a table, but I want to customize the items inside the list.)
 + Here, I want to take advantage of [`QListView.Movement = QListView.Free`](https://doc.qt.io/qt-5/qlistview.html#Movement-enum) to enable changing the priority of experiments in the scheduler GUI. But if this does not work, then I would try hardcoding the drag & drop property later.

An isolated frame (for displaying the current experiment) and this `QListView` will contain instances of the class `ExperimentView`, which will be later implemented (mentioned in [Discussion#62](https://github.com/snu-quiqcl/iquip/discussions/62#discussion-5377377) and will be implemented through [Issue#64](https://github.com/snu-quiqcl/iquip/issues/64#issue-1793898710)).

**Comment by BECATRUE** [comment]
> Here, I want to take advantage of QListView.Movement = QListView.Free to enable changing the priority of experiments in the scheduler GUI. But if this does not work, then I would try hardcoding the drag & drop property later.

It looks so cool property!
However, I'm worried that changing the priority looks difficult, and I think you should cancel the experiment and re-sumbit it.
If you think it would become a big implementation, you can separate into several issues!

**Comment by giwon2004** [comment]
Oh, I did not know that changing priorities is a big deal.

If it is, I guess I can implement everything except this drag & drop feature first, and then try it.
