### ISSUE TITLE
TTL Monitor Plan

### ISSUE THREAD

**Issue by nick11967** [snu-quiqcl/iquip#79]
### Feature you want to implement
- TTL Monitor Plan
  - I will post some image or discription of TTL Monitor
  - Improve the idea with feedback
- Implement TTL Monitor based on this idea

### Additional context
- I'm checking TTL signals that I would use in Monitor

**Comment by BECATRUE** [comment]
@nick11967 

Please write more details in the discussion tab!
There are several plans for other projects such as explorer, builder, etc.

**Comment by nick11967** [comment]
Come to think of it, I relased that I can just write a plan on 'Implement' issue and get feedback there. I'll close this issue and talk more about the TTL monitor on issue #80.
