### ISSUE TITLE
Implement TTL Monitor

### ISSUE THREAD

**Issue by nick11967** [snu-quiqcl/iquip#80]
### Feature you want to implement
~~TTL Monitor based on idea on previous issue(#79)~~
A widget to monitor TTL input and output

### How the feature is implemented
On the `TTLMonitorWidget', update when TTL signals change.
I guess by following code below will be helpful.
[artiq/dashboard/moninj](https://github.com/m-labs/artiq/blob/df15f53ee97558b31c23a3bbe93f32c14b18fe74/artiq/dashboard/moninj.py#L33)

**Comment by kangz12345** [comment]
Since this is not completed, please use "Close as not planned".
