### ISSUE TITLE
Implement unit test for logger app

### ISSUE THREAD

**Issue by Aijuh** [snu-quiqcl/iquip#83]
### Feature you want to implement
Implement unit test for the logger.py.

### Plan for implementing feature.
1. Make test functions for class methods in LoggerApp. (If it don't change any variable, I will check whether specific function is called.) 

2. Make sure all the signals are connected to the proper function. (I am planning to call signal.emit and whether connected class method is called.)

### Additional context
If I missed something please let me know.

**Comment by BECATRUE** [comment]
I changed the label into `test`!
