### ISSUE TITLE
Implement a result explorer

### ISSUE THREAD

**Issue by BECATRUE** [snu-quiqcl/iquip#93]
### Feature you want to implement
We need an explorer to show the result path through the proxy server.
For this, I will implement `ResultExplorerApp`, similar to `ExplorerApp`.

In this app, there are the following functions.
- After receiving the result path structure, add each RID in the explorer.
snu-quiqcl/artiq-proxy#38
- Add a `QTreeWidget` to show the submission info i.e., build argumetns, priority, due date, etc. of the clicked RID.
snu-quiqcl/artiq-proxy#57
- Add a button to reload the structure.
- Add a button to open the specific visualization result.

### How the feature is implemented
According to snu-quiqcl/artiq-proxy#36, in the result path, there are only directories with an RID name, not files.
(It means that the structure is flat.)
Thus, I will show the structure using `QListWidget`.

And for showing the submission info, I will add a `QTreeWidget` under the `QListWidget`.
Once an user clickes a specific RID, the submission info viewer would be updated.

**Comment by kangz12345** [comment]
How about "ResultExplorer" instead of "VisualizeExplorer"?
I think we can add more features for it, e.g., link to data viewer, etc.
The essence of it is, in my opinion, exploring the experiment results.

**Comment by BECATRUE** [comment]
> How about "ResultExplorer" instead of "VisualizeExplorer"? I think we can add more features for it, e.g., link to data viewer, etc. The essence of it is, in my opinion, exploring the experiment results.

@kangz12345 
Umm.. "ResultExplorer" looks different from "VisualizeExplorer" because even if the experiment was not visaulized, the result is always generated.

**Comment by BECATRUE** [comment]
However, I still hope to find out more appropriate name of this app, too!

**Comment by kangz12345** [comment]
Oh.. I thought the h5 files will also be saved in those directories. Then currently only vcd files are included?
If we want to explore the h5 files, should the data viewer app implement another explorer?

**Comment by BECATRUE** [comment]
As @kangz12345 and I discussed, I updated this plan!
