### ISSUE TITLE
Dataset Table Viewer

### ISSUE THREAD

**Issue by yennieday2** [snu-quiqcl/iquip#97]
### Feature you want to implement
View the given data as a table

### How the feature is implemented
Given the number of rows and columns by the user, the viewer shows the data as a table in the desired size

### Additional context
![image](https://github.com/snu-quiqcl/iquip/assets/99079226/06089040-b4f6-4eb7-8a1b-ce5d2a8dcbf9)

**Comment by kangz12345** [comment]
Let's define the input specification in more detail.
How will you take the input? For example, h5 file, 2d array, etc.

**Comment by kangz12345** [comment]
In addition, I would like to set the labels for rows and columns (e.g., "time (us)", "position (mm)", etc.).

**Comment by BECATRUE** [comment]
@yennieday2
