### ISSUE TITLE
Dataset Plot Viewer

### ISSUE THREAD

**Issue by yennieday2** [snu-quiqcl/iquip#98]
### Feature you want to implement
View the given data as a plot

### How the feature is implemented
Given the input count by the user, the viewer shows the data as a 2D plot in the desired size.
The plot will be drawn with the real-time update system.

### Additional context
![image](https://github.com/snu-quiqcl/iquip/assets/99079226/4244a578-3c79-4251-949b-d3ce94a754f4)

**Comment by BECATRUE** [comment]
@kangz12345 Now, is it okay to close issues about the dataset project?

**Comment by kangz12345** [comment]
> @kangz12345 Now, is it okay to close issues about the dataset project?

Okay. I will create new issues as I take the dataset project from now on.
